# Generated by Django 4.2.7 on 2023-11-13 07:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_tag_project_vote_ratio_project_vote_totoal_review_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="vote_totoal",
            new_name="vote_total",
        ),
    ]
